#! /usr/bin/env bash
#
# SPDX-License-Identifier: MIT


_ps1_background_jobs()
{
    local -i running stopped

    exec 3<>"$1"

    jobs -pr >&3
    while read -t 0 -u 3; do
        read -ru 3
        running+=1
    done
    jobs -ps >&3
    while read -t 0 -u 3; do
        read -ru 3
        stopped+=1
    done

    if ((running + stopped)); then
        printf '['
        colors.purple --bold --escape; printf '%i' "$running"; colors.default --escape
        printf '/'
        colors.pink --bold --escape; printf '%i' "$stopped"; colors.default --escape
        printf ']'
    fi

    exec 3>&- 3<&-
}
