#! /usr/bin/env bash
#
# SPDX-License-Identifier: MIT

_ps1_classic()
{
    # Colors
    local -a colors_=("${!colors[@]}")
    local color="${colors_[SHLVL % ${#colors_[@]}]}"

    # Basic look: [username current_directory]
    printf '['; colors."$color" --escape; printf '\\u'; colors.default --escape; printf ' \W]'
}
