#! /usr/bin/env bash
#
# SPDX-License-Identifier: MIT

_ps1_classic()
{
    # Colors
    local -a colors_=(default pink green yellow blue red purple)
    local color="${colors_[SHLVL % ${#colors_[@]}]}"

    # Basic look: [username current_directory]
    printf '['; "$color" --escape; printf '\\u'; default --escape; printf ' \W]'
}
