#! /usr/bin/env bash
#
# SPDX-License-Identifier: MIT

_ps1_git_dirtyness()
{
    local git_dir
    _git_dir || return 0

    local -i staged=0 unstaged=0 untracked=0
    local status

    while IFS='' read -r status; do
        [[ ${status:0:2} == \?\? ]] && { untracked+=1; continue; }
        [[ ${status:0:1} != " " ]] && staged+=1
        [[ ${status:1:1} != " " ]] && unstaged+=1
    done < <(git status --porcelain)

    [[ $staged -eq 0 ]] && [[ $unstaged -eq 0 ]] && return

    printf '['
    colors.green --escape; printf '%d' "$staged"; colors.default --escape
    printf '|'
    colors.red --escape; printf '%d' "$unstaged"; colors.default --escape
    printf '|'
    colors.orange --escape; printf '%d' "$untracked"; colors.default --escape
    printf ']'
}
