#! /bin/bash
#
# SPDX-License-Identifier: MIT
#
# author: ypsah <asyph@tutanota.com>

_ps1_git_dirtyness()
{
    _is_git || return

    local -i staged=0 unstaged=0 untracked=0
    local status

    while IFS='' read -r status; do
        [[ ${status:0:2} == \?\? ]] && { untracked+=1; continue; }
        [[ ${status:0:1} != " " ]] && staged+=1
        [[ ${status:1:1} != " " ]] && unstaged+=1
    done < <(git status --porcelain)

    [[ $staged -eq 0 ]] && [[ $unstaged -eq 0 ]] && return

    printf '['
    green --escape; printf '%d' "$staged"; default --escape
    printf '|'
    red --escape; printf '%d' "$unstaged"; default --escape
    printf '|'
    orange --escape; printf '%d' "$untracked"; default --escape
    printf ']'
}
