#! /bin/bash
#
# SPDX-License-Identifier: MIT
#
# author: ypsah <asyph@tutanota.com>

_ps1_return_code()
{
    printf '['
    if (($1 == 0)); then
        green --escape
    else
        orange --bold --escape
    fi
    printf '$?'
    default --escape
    printf ']'
}
