#! /bin/bash
#
# SPDX-License-Identifier: MIT
#
# author: ypsah <asyph@tutanota.com>

_ps1_return_code()
{
    PS1+="["
    [[ $1 -eq 0 ]] && PS1+="$(green -e)" || PS1+="$(orange -be)"
    PS1+="\$?$(default -e)]"
}
