#! /usr/bin/env bash
#
# SPDX-License-Identifier: MIT

_ps1_return_code()
{
    printf '['
    if (($1 == 0)); then
        colors.green --escape
    else
        colors.orange --bold --escape
    fi
    printf '$?'
    colors.default --escape
    printf ']'
}
