#! /usr/bin/env bash
#
# SPDX-License-Identifier: MIT

declare -Ax colors=(
    [default]=39

    [red]=31
    [green]=32
    [yellow]=33
    [blue]=34
    [magenta]=35
    [cyan]=36
    [gray]=37

    [purple]="38;5;99"
    [pink]="38;5;205"
    [orange]="38;5;208"
)

colors._color()
{
    local escape=false
    local -i bold=0

    while [[ $# -gt 0 ]]; do
        [[ $1 =~ ^-[^-]. ]] && set -- "${1:0:2}" "-${1:2}" "${@:2}" 
        case "$1" in
        -e|--escape)
            escape=true
            ;;
        -b|--bold)
            bold=1
            ;;
        *)
            break
            ;;
        esac
        shift
    done

    $escape && printf '\['
    printf '\e[%i;%sm' "$bold" "$1"
    $escape && printf '\]'

    return 0
}

export -f colors._color

for color in "${!colors[@]}"; do
    eval "colors.$color() { colors._color "'"$@"'" \"${colors[$color]}\"; }; export -f colors.$color"
done

colors.colorize()
{
    local -a options
    [[ -v escape ]] && $escape && options+=(--escape)

    case $# in
    0)
        return
        ;;
    1)
        string="$("$1" "${options[@]}")$string"
        ;;
    *)
        local tmp="$string"
        string=""

        local -i i=1
        while [[ $tmp ]]; do
            string+="$("${!i}" "${options[@]}")${tmp:0:1}"
            tmp="${tmp:1}"
            ((i++ == $#)) && i=1
        done
    esac

    string+="$(default "${options[@]}")"
}

export -f colors.colorize
