#! /bin/bash
#
# SPDX-License-Identifier: MIT

exit()
{
    local -i code=${1:-$?}
    shift || true

    exec 2>&1

    case "$code" in
    64) # EX_USAGE
        declare -F usage >/dev/null 2>&1 && usage
        [[ $# -gt 0 ]] && printf '\n'
        ;;
    esac

    [[ $# -gt 0 ]] && printf "%s: $1\n" "${BASH_SOURCE[1]##*/}" "${@:2}"

    builtin exit "$code"
}

export -f exit
