#! /bin/bash
#
# SPDX-License-Identifier: MIT
#
# author: ypsah <asyph@tutanota.com>

_cd()
{
    local cur prev words cword
    _init_completion &>/dev/null || {
        complete -o dirnames cd
        return
    }

    local arg
    _get_first_arg

    case "$arg" in
    history)
        return
        ;;
    clean)
        [[ $prev == "clean" ]] || return
        COMPREPLY=($(compgen -W 'all old' -- "$cur"))
        return
        ;;
    "")
        _filedir -d
        if [[ -z $cur && ${#COMPREPLY[@]} -gt 0 ]]; then
            local reply letter="${COMPREPLY[0]:0:1}"
            for reply in "${COMPREPLY[@]:1}"; do
                [[ ${reply:0:1} != "$letter" ]] && break 2
            done
            return
        fi
        COMPREPLY+=($(compgen -W 'clean history' -- "$cur"))
        ;;
    esac
} && complete -F _cd cd
