#! /bin/bash
#
# SPDX-License-Identifier: MIT
#
# author: ypsah <asyph@tutanota.com>

_vault_remove()
{
    _filedir
}

_vault_stash()
{
    _filedir
}

_vault()
{
    local cur prev words cword
    _init_completion

    local arg
    _get_first_arg

    if [[ $arg ]]; then
        local func

        printf -v func '_vault_%s' "$arg"
        declare -F "$func" >/dev/null && "$func"
        return
    fi

    local -a actions=(create seal stash remove)
    COMPREPLY=($(compgen -W '${actions[*]}' -- "$cur"))
}

complete -F _vault vault
